# Generated by Django 4.0.3 on 2022-05-17 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_transaction_second_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='atm_card',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cvv2',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='app.bankaccount', to_field='account_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_card',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_card', to='app.bankaccount', to_field='atm_card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='atm_card',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_card',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
