# Generated by Django 4.0.3 on 2022-05-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_transaction_atm_card_remove_transaction_cvv2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_card',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='app.bankaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='atm_card',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, related_name='from_card', to='app.bankaccount'),
            preserve_default=False,
        ),
    ]
