# Generated by Django 4.0.3 on 2022-05-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_transaction_from_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_account',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='atm_card',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.bankaccount'),
        ),
    ]
