# Generated by Django 4.0.3 on 2022-05-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_transaction_atm_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
