# Generated by Django 4.0.3 on 2022-05-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='atm_card',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_card',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='atm_card',
            field=models.CharField(max_length=16),
        ),
    ]
