# Generated by Django 4.0.3 on 2022-05-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_transaction_atm_card_transaction_from_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='credit',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
