# Generated by Django 4.0.3 on 2022-05-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_bankaccount_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('TR', 'Transfer'), ('RE', 'Recharge'), ('CH', 'Charity')], default='TR', max_length=2),
            preserve_default=False,
        ),
    ]
