# Generated by Django 4.0.3 on 2022-05-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rem_credit',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=19),
            preserve_default=False,
        ),
    ]
