# Generated by Django 4.0.3 on 2022-05-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_transaction_rem_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='to_card',
            new_name='recipient',
        ),
    ]
