# Generated by Django 4.0.3 on 2022-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_bankaccount_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rem_credit',
            field=models.PositiveBigIntegerField(),
        ),
    ]
